### ISSUE TITLE
KeyMapping: gvim において lhs: ^?  なマッピングに対応してない

### ISSUE THREAD

**Issue by haya14busa** [osyo-manga/vital-palette#5]
lingrのログ(一応): http://lingr.com/room/vim/archives/2015/04/10#message-21642378
#### マッピング

https://gist.githubusercontent.com/anekos/f15ce166cb940dab4ce9/raw/33cde551878dc4fb545f2d7062d0c368ffebbdfb/gistfile1.txt

ブラウザでは見えないですが `^?` がlhsになってる.

これをpaletteのKeyMappingに食わせると対応できずに普通の文字の`maparg('<^?>', モード, 0, 1)`を実行して結果が`{}`になってしまいます.

**Comment by haya14busa** [comment]
![](http://i.gyazo.com/a6fd48650f774924200e0387dd278afd.png)

これが`redir`によって区別されなくなるのでそもそも対応できないのでゎ...説まであるかもです

**Comment by haya14busa** [comment]
と，思ったけどそれは普通の`<C-h>` とかを `<` + `C` + ...の連続マッピングで定義した時も同じか.

**Comment by osyo-manga** [comment]
ありがとうございます。
んー確かにこの問題は `redir` 使ってる限り解決できなさそうですねぇ。

**Comment by osyo-manga** [comment]
ちなみに `^?`（特殊文字）はこっちだと `<C-?>` でした。

**Comment by osyo-manga** [comment]
とりあえず、`<C-?>` の場合の対処はしてみました。
ただ、 @haya14busa さんも書いてましたが、`<^?>` （特殊文字ではない）との区別ができない問題は残っています。

**Comment by osyo-manga** [comment]
`<^?>` の方も対処するとしたら `maparg("\<C-?>")` と `maparg("<^?>")` の結果と `:map` の出力結果を比較してどっちがどっちなのかを比較するみたいな感じになると思います。

**Comment by haya14busa** [comment]
対応ありがとうございますっ!

あー`\<C-?>`でしたか...なんで気づかなかったんだろう．なるほど感が高い．

**Comment by haya14busa** [comment]
特殊文字と単なる連続の区別は実用的には正直いらなさそうですね(自分でいっておいて

**Comment by osyo-manga** [comment]
![](http://i.gyazo.com/62514a1f26c969963a0d487d14fe0dc9.png)

**Comment by haya14busa** [comment]
ところで今KeyMappingのテスト落ちてると思いますが再現します?

**Comment by haya14busa** [comment]
```vim
let s:V = vital#of('vital')
let s:K = s:V.import('Palette.Keymapping')
echo s:K.parse_lhs("x  <C-A>       * <C-C>ggVG")
```

これが落ちてるのと, 7.3(travisのvimのバージョン)で `s:test_keymapping()` が落ちてるっぽい

(簡易しらべ) https://travis-ci.org/haya14busa/vital-palette/builds/58137656

**Comment by osyo-manga** [comment]
あーすみません、こちらでも確認しました。
落ちてる原因がわかったので修正します（あとバグも見つけたので治す

**Comment by haya14busa** [comment]
`call extend(l:, get(a:, 1, {}))` 7.3はこれが対応してないというアレだった(Capture.vimのcommand)

**Comment by haya14busa** [comment]
`extend`を直すのはこんな感じですね(一応) https://github.com/haya14busa/vital-palette/commit/f43dae6abc6bd9b501d6f495faf7ec61b489c482

**Comment by osyo-manga** [comment]
> extendを直すのはこんな感じですね(一応) haya14busa@f43dae6

ありがとうございます。
7.3 って 7.3.000 でしょうか？（マイナーバージョンが知りたい

**Comment by osyo-manga** [comment]
正直 7.3.000 であれば結構古いので、どうしても動かしたい！と要望がなければ非サポートでもいいかなーとは思います。
（ここ以外のコードが 7.3.000 で問題なく動作しているのかが保証できないのもありますが・・・。
あと具体的にどこが問題なのかわからないんですが、`extend()` をラッパーして対処できる問題であれば、どこかに `extend()` のラッパーを用意したいところですね。
（そもそも `l:` 自体が不変であったり、関数の引数に渡せないような問題ならダメですが。

**Comment by osyo-manga** [comment]
とりあえず、`expand()` 以外でテストが失敗してたので、そちらは修正しました。
ありがとうございました。

**Comment by haya14busa** [comment]
ちなみにそれだとvital-overの必要バージョンも下げることになります．(ｼﾞｯｻｲこれはincsearch.vimのtravisのテストが落ちたことで気づいた)

正確にいうと 7.3.429 (travisのデフォルト，つまりは確かUbuntuあたりのデフォルトVimバージョン)を切り捨てることになるので，対応できる問題なら対応してほしいです

**Comment by haya14busa** [comment]
そして対応ありがとうございます

**Comment by haya14busa** [comment]
> （ここ以外のコードが 7.3.000 で問題なく動作しているのかが保証できない

(7.3.xxx と読み替えて) だからtravisで動かしたいんですよね〜(ﾁﾗｯ

**Comment by haya14busa** [comment]
`extend()`のラッパーは, 関数内スコープを拡張するという意図が前提としてあるので不可能だと思います．

**Comment by osyo-manga** [comment]
いえ、`l:` を変更する事ができるのであればできます。

```vim
function! s:extend(dict, src)
	for [key, value] in items(a:src)
		let a:dict[key] = value
	endfor
endfunction

function! s:main()
	call s:extend(l:, { "value" : 42, "name" : "homu" })
	echo value
	echo name
endfunction
call s:main()
```

**Comment by osyo-manga** [comment]
travis の Vim のバージョンっていくつなのでしたっけ

**Comment by haya14busa** [comment]
`l:`を変更することができないというのが古いVimの問題です

**Comment by haya14busa** [comment]
travisのVimﾊﾞｰｼﾞｮﾝ: 7.3.429 https://travis-ci.org/haya14busa/vital-palette/jobs/58137658#L335

**Comment by osyo-manga** [comment]
あーすみません、コメ連投されているのにいま気づきました。

**Comment by haya14busa** [comment]
> l:を変更することができないというのが古いVimの問題です

とは言ったものの，おしょーさんのコードは試してないのでわからん(ただ以前にたようなことをやってみたことがあるので，できないはず)(now 7.3 ローカル環境構築ing...)

**Comment by osyo-manga** [comment]
ubuntu って 14 系でもまだデフォルトの Vim が 7.3 系なのでしたっけ？（ubuntu 使ってるけどよく知らない勢。

**Comment by haya14busa** [comment]
14系がどうかはよくしらないですね．上がっていたような気もするけどどうだろう

**Comment by haya14busa** [comment]
まぁどちらにせよ対応していただけないのであれば僕はforkします(僕はまだ7.3対応しておきたい)

**Comment by haya14busa** [comment]
...!

**Comment by haya14busa** [comment]
おしょーさんの`s:extend()`, 7.3対応してるっぽい...!

**Comment by osyo-manga** [comment]
とりあえず、対応はしようと思います。

> おしょーさんのs:extend(), 7.3対応してるっぽい...!

便利そう。

**Comment by haya14busa** [comment]
べんりすぎる...`l:`が変更できないっていうのは`extend()`だけだったのか. 勘違いしてましたもうしわけないです

**Comment by haya14busa** [comment]
`unlet value`だけしておく必要がありそうですね

**Comment by osyo-manga** [comment]
> unlet valueだけしておく必要がありそうですね

これ、どこの部分でしょうか？
`s:extend()` 内で `unlet` しても意味はないと思うのですが。

**Comment by haya14busa** [comment]
https://gist.github.com/haya14busa/ce797bb2f1197bc84a3c

こんなかんじです．`unlet` ないとtype missmatchでエラー吐きます(インデントは気にしないでください)

**Comment by haya14busa** [comment]
もしくは`keys()`にして, 変数を介さない方法でもok

```vim
function! s:_extend(dict, src)
	for key in keys(a:src)
		let a:dict[key] = a:src[key]
	endfor
endfunction
```

**Comment by osyo-manga** [comment]
ああーそういえば、そうでした。

**Comment by osyo-manga** [comment]
とりあえず、対応してみました。
これでちょっと試してもらえないでしょうか。

**Comment by haya14busa** [comment]
7.3で通りましたっ! https://travis-ci.org/haya14busa/vital-palette/jobs/58145892#L334

対応ありがとうございますっ

**Comment by osyo-manga** [comment]
ありがとうございます。
この `extend()` どこまで対応するのか迷うな…（第三引数とかリストの対応とか…。
これ、実は `s:extend()` 内で `extend(a:dict, a:src)` すれば動作するとか無いですかね。

**Comment by haya14busa** [comment]
なかったです(やってみた)

**Comment by haya14busa** [comment]
どこまで対応するかは任せます(そもそも，`l:` とかextendするとき以外はデフォルトで十分なので僕だったらいらないのでゎと思いました．あるとしたら第三引数の`keep`対応はもしかしたら欲しい人もいるかもですが)

**Comment by osyo-manga** [comment]
残念。
まぁ現状 `l:` でしか問題ないならそのままでもよいかなぁ。

**Comment by haya14busa** [comment]
テストも通ってるし，このissueとしては閉じます．ありがとうございましたっ
